import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  heroImage: Media
  blockImage: Media
  author: User
}

export const post4: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'badkamer-sloop-guide',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Een badkamerrenovatie begint altijd met een grondige en professionele sloop van de bestaande ruimte. Dit is een complex proces dat vakkennis, precisie en de juiste werkwijze vereist. In deze uitgebreide gids nemen wij u stap voor stap mee door het volledige badkamersloopproces.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Met meer dan 25 jaar ervaring in badkamersloop hebben wij tienduizenden badkamers succesvol gedemonteerd. Van kleine toiletruimtes tot luxe badkamercomplexen in hotels - wij weten precies wat er komt kijken bij professionele badkamersloop.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Voorbereiding en Veiligheid: De Basis van Succes',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Een veilige badkamersloop begint met een grondige voorbereiding. Onze experts inspecteren eerst de ruimte om alle potentiele risicos in kaart te brengen. Dit omvat het identificeren van waterleidingen, electra, ventilatiekanalen en mogelijk asbesthoudende materialen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Veiligheidsmaatregelen die wij treffen omvatten: het volledig afsluiten van water en elektra, het aanleggen van afzettingen en waarschuwingsborden, het plaatsen van ventilatie voor afvoer van stof en dampen, het gebruik van persoonlijke beschermingsmiddelen zoals veiligheidsbrillen, handschoenen en stofmaskers, en het beschermen van vloeren en omliggende ruimtes met speciale afdekfolie.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Bij oudere badkamers uit voor 1993 is er kans op asbest in kitnaden, tegellijm of vloerbedekking. Wij voeren altijd een asbestinventarisatie uit voordat we beginnen. Indien asbest wordt aangetroffen, wordt de verwijdering uitgevoerd door gecertificeerde asbestsaneerders volgens de strengste veiligheidsnormen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap-voor-Stap: Het Sloopproces',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ons badkamersloopproces volgt een strikt protocol dat is ontwikkeld op basis van jarenlange ervaring. Elke stap wordt zorgvuldig uitgevoerd om schade aan leidingen en constructies te voorkomen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 1: Sanitair en losse onderdelen verwijderen. We beginnen met het demonteren van alle losse en vastzittende sanitair: wc, wastafel, douchebak, bad, kraanwerk en accessoires. Deze worden zorgvuldig losgekoppeld van waterleidingen en afvoeren. Herbruikbare onderdelen worden apart gezet.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 2: Tegels en wandafwerking slopen. Vervolgens verwijderen we de wandtegels en eventuele badkamermeubels. Dit gebeurt met speciale gereedschappen om de ondergrond zo veel mogelijk te beschermen. Hardnekkige tegellijm wordt mechanisch verwijderd.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 3: Vloer slopen en afvoeren. De badkamervloer wordt verwijderd tot op de draagconstructie. Dit kan tegels, vinyl, beton of gietvloer betreffen. We letten extra op vloerverwarming en leidingen die in de vloer kunnen liggen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 4: Leidingen en electra veilig afkappen. Waterleidingen worden op de juiste manier afgekapt en afgedicht met professionele stoppen. Elektraleidingen worden spanningsvrij gemaakt en veilig afgekapt. Afvoerleidingen worden voorzien van tijdelijke afsluiters.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Technische Aspecten en Vakmanschap',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Badkamers zijn technisch complexe ruimtes met veel verborgen leidingen en systemen. Onze vakmensen hebben gedegen kennis van loodgieterswerk en electrotechniek om alles correct en veilig te behandelen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Speciale aandacht vereisen: leidingen van de centrale verwarming die door de badkamer lopen, electrale groepen die specifiek voor de badkamer zijn aangelegd, ventilatiesystemen en afvoerkanalen, dragende wanden en vloerconstructies, en waterdichte folielagen en isolatie.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Onze ervaring leert dat voorzichtigheid geboden is bij het verwijderen van oude voegen en kit. Hier kan asbest in zitten. We nemen monsters en laten deze analyseren voordat we verder gaan met sloopwerkzaamheden.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Afvalscheiding en Duurzame Verwerking',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Duurzaamheid staat centraal in onze werkwijze. Tijdens de badkamersloop scheiden we alle materialen zorgvuldig. Keramisch sanitair wordt verwerkt tot granulaat voor wegenbouw, metalen gaan naar de recycler, en kunststoffen worden gesorteerd per type voor hergebruik.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'We streven naar een recyclingpercentage van minimaal 90% voor badkamersloopprojecten. Door zorgvuldige scheiding op de bouwplaats voorkomen we dat bruikbare materialen op de stort belanden. Dit bespaart kosten en draagt bij aan een circulaire economie.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Schoonmaak en Oplevering',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Na voltooiing van de sloopwerkzaamheden voeren we een grondige schoonmaak uit. Alle bouwresten, stof en puin worden verwijderd. De ruimte wordt veegklaar opgeleverd, zodat uw aannemer direct kan starten met de nieuwbouw.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Onze oplevering omvat: verwijdering van alle sloopafval en containers, stofvrij maken van alle oppervlakken, inspectie van leidingen en electra op juiste afsluiting, bescherming van kostbare vloeren en wanden in omliggende ruimtes, en een opleveringsdocument met foto's en verwerkingsbewijzen van afvalstromen.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wanneer Professionele Hulp Inschakelen?',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Hoewel sommige klanten overwegen zelf te slopen, raden wij voor badkamers professionele hulp aan. De complexiteit van leidingen, het risico op waterschade, en de mogelijke aanwezigheid van asbest maken badkamersloop een vak apart.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Professionele badkamersloop biedt: garantie op vakmanschap en veiligheid, verzekerde dekking voor eventuele schade, juiste afhandeling van asbest en gevaarlijke stoffen, efficiëntie en snellere oplevering, en duurzame verwerking van alle materialen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Conclusie: Vertrouw op de Professionals',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Een professionele badkamersloop vormt het fundament voor een succesvolle renovatie. Door te kiezen voor TitanBreakers kiest u voor 25 jaar ervaring, vakmanschap en zorgvuldigheid. Wij garanderen een veilige, efficiënte en duurzame sloop die perfect aansluit op de bouw van uw nieuwe badkamer.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Neem vandaag nog contact met ons op voor een vrijblijvende offerte. Onze experts komen graag bij u langs om de situatie te beoordelen en een gedetailleerd plan op te stellen. Met TitanBreakers bent u verzekerd van kwaliteit en gemoedsrust.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Complete gids voor professionele badkamersloop. Lees alles over veiligheid, het sloopproces stap-voor-stap en duurzame afvalverwerking.',
      image: heroImage.id,
      title: 'Professionele Badkamer Sloop: Stap-voor-Stap Gids',
    },
    relatedPosts: [],
    title: 'Professionele Badkamer Sloop: Stap-voor-Stap Gids',
  }
}
