import { RequiredDataFromCollectionSlug } from 'payload'
import type { PostArgs } from './post-1'

export const post3: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: '25-jaar-titanbreakers',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Dit jaar vieren wij een bijzondere mijlpaal: 25 jaar TitanBreakers! Van een klein familiebedrijf met één sloopmachine zijn wij uitgegroeid tot een toonaangevend demontagebedrijf dat door heel Nederland operaties uitvoert. In dit jubileumartikel nemen wij u mee op onze inspirerende reis vol groei, innovatie en duurzaamheid.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De afgelopen 25 jaar hebben wij duizenden projecten succesvol afgerond, van kleine badkamersloots tot grootschalige industriële demontages. Onze missie is altijd hetzelfde gebleven: veilige, efficiënte en duurzame sloopoplossingen leveren die onze klanten volledig ontzorgen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De Oprichting: Een Droom Wordt Werkelijkheid',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Het verhaal van TitanBreakers begint in 1999, toen oprichter Jan van den Berg met één sloopmachine en een droom startte vanuit een kleine schuur in Amsterdam. Met jarenlange ervaring in de bouw zag hij de behoefte aan professionele, klantgerichte sloopdiensten die de regels van het vakbouw respecteerden.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De eerste jaren waren hard werken. Jan combineerde sloopwerkzaamheden met administratie en klantcontact. Zijn vrouw Maria hield de boekhouding bij. Toch groeide het bedrijf gestaag dankzij mond-tot-mondreclame en tevreden klanten die onze zorgvuldige aanpak waardeerden.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Binnen vijf jaar hadden we al een team van tien vakmensen en onze eerste echte bedrijfspand. De naam TitanBreakers was geboren uit de gedachte dat wij als sloopbedrijf net zo krachtig en betrouwbaar moesten zijn als een titaan, maar met de precisie en zorg van een vakman.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Belangrijke Mijlpalen en Groei',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In 2005 bereikten we onze eerste grote mijlpaal: de demontage van een compleet industrieterrein van 50.000 vierkante meter in Rotterdam. Dit project toonde aan dat wij meer waren dan alleen een klein sloopsbedrijf. We hadden de expertise en capaciteit voor grootschalige opdrachten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '2008 was een belangrijk jaar voor onze professionalisering. We behaalden alle benodigde certificeringen waaronder VCA**, BRL SVS-001 voor asbestsanering, en ISO 14001 voor milieumanagement. Deze certificeringen openden deuren naar grote opdrachtgevers en complexe projecten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De jaren 2010-2015 kenmerkten zich door snelle expansie. We openden vestigingen in Utrecht, Eindhoven en Groningen. Ons wagenpark groeide tot 50 gespecialiseerde sloopmachines en transports. Het team breidde uit naar meer dan 100 medewerkers, allemaal geschoolde vakmensen met passie voor het vak.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Innovatie en Duurzaamheid als Pijlers',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Vanaf 2015 zetten we extra stappen in duurzaamheid en innovatie. We investeerden zwaar in elektrisch materieel, stofafzuigsystemen en geavanceerde sorteerinstallaties. Ons doel was ambitieus: 98% van alle sloopmaterialen recycleren en CO2-neutraal opereren in 2025.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In 2018 introduceerden we ons unieke circulaire sloopconcept. Door materialen direct op de bouwplaats te sorteren en te verwerken, sluiten we de kringloop en besparen we transportbewegingen. Dit concept werd bekroond met de Nationale Bouwprijs voor Duurzaamheid.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De afgelopen jaren hebben we onze digitale transformatie doorgevoerd. Met 3D-scanning, BIM-integratie en real-time projectmanagement apps kunnen we onze klanten nog beter bedienen. Technologie maakt ons slimmer, sneller en veiliger.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Terugblik: Trots op Onze Projecten',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In 25 jaar hebben we meer dan 10.000 projecten succesvol afgerond. Enkele hoogtepunten die ons bijzonder trots maken: de renovatie van het Amstel Hotel in Amsterdam waarbij we het interieur volledig vernieuwden zonder gasten te storen, de demontage van de oude Philips-fabrieken in Eindhoven met 99% recyclingpercentage, en het asbestsaneringsproject op Schiphol dat binnen de strengste veiligheidsnormen werd uitgevoerd.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ook kleine projecten hebben onze volledige aandacht gekregen. Duizenden keukens, badkamers en woonkamers hebben we gesloopt om plaats te maken voor nieuwe dromen. Elk project, groot of klein, verdient de beste aanpak en de hoogste kwaliteit.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De Toekomst: Duurzaam Groeien en Innoveren',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Terwijl we ons 25-jarig jubileum vieren, kijken we ook vooruit naar de toekomst. Onze ambitie is om de komende vijf jaar door te groeien naar een landelijk dekkend sloopbedrijf met 200 medewerkers, terwijl we onze kernwaarden behouden.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Onze toekomstvisie omvat: 100% CO2-neutrale operaties in 2030, verdere automatisering en robotisering van sloopwerkzaamheden, uitbreiding naar de grensregio met vestigingen in België en Duitsland, en ontwikkeling van een eigen opleidingscentrum voor jong talent in de sloopsector.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'We blijven investeren in onze mensen. Vakmanschap, veiligheid en klanttevredenheid staan centraal in al onze opleidingsprogrammas. Want uiteindelijk zijn het onze medewerkers die het verschil maken bij elk project.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Dank aan Onze Klanten en Medewerkers',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Dit jubileum is niet alleen van TitanBreakers, maar van iedereen die ons heeft geholpen om hier te komen. We bedanken onze trouwe klanten die ons jaar na jaar hun vertrouwen geven. Jullie feedback en samenwerking hebben ons gevormd tot wie we vandaag zijn.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ook onze medewerkers verdienen een speciaal woord van dank. Velen van jullie zijn al jaren, soms zelfs decennia, bij ons in dienst. Jullie toewijding, vakmanschap en inzet zijn de fundamenten van ons succes. Samen hebben we niet alleen gebouwen gesloopt, maar ook een hechte TitanBreakers-familie gebouwd.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Vier het Met Ons Mee!',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ter gelegenheid van ons 25-jarig jubileum bieden wij speciale jubileumkortingen aan op al onze sloopdiensten gedurende het hele jaar. Daarnaast organiseren we in oktober een open dag op onze hoofdvestiging waar u kennis kunt maken met onze machines, methoden en mensen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wilt u meer weten over onze geschiedenis, toekomstplannen of een vrijblijvende offerte voor uw sloopproject? Neem contact met ons op. We kijken ernaar uit om de komende 25 jaar met u samen te bouwen aan een duurzame toekomst. Op naar de volgende 25 jaar TitanBreakers!',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Vier met ons mee 25 jaar TitanBreakers! Lees over onze groei van familiebedrijf naar nationaal sloopbedrijf en onze toekomstvisie.',
      image: heroImage.id,
      title: '25 Jaar TitanBreakers: Onze Inspirerende Reis',
    },
    relatedPosts: [],
    title: '25 Jaar TitanBreakers: Onze Inspirerende Reis',
  }
}
