import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  heroImage: Media
  blockImage: Media
  author: User
}

export const post1: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'handmatige-vs-mechanische-sloop',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Bij het slopen van gebouwen en constructies staat u voor een belangrijke keuze: handmatige sloop of mechanische sloop. Deze beslissing heeft significante gevolgen voor de veiligheid, kosten, snelheid en milieu-impact van uw project. In dit artikel leggen we beide methoden uit zodat u een weloverwogen keuze kunt maken.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Als professioneel sloopbedrijf met meer dan 25 jaar ervaring hebben wij duizenden projecten succesvol uitgevoerd met zowel handmatige als mechanische technieken. Onze expertise stelt ons in staat om voor elke situatie de optimale aanpak te bepalen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wanneer Kiezen voor Handmatige Sloop?',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Handmatige sloop is de traditionele methode waarbij gespecialiseerde vakmensen met handgereedschap en lichte machines het sloopwerk uitvoeren. Deze methode is bijzonder geschikt voor situaties waar precisie en controle essentieel zijn.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De ideale toepassingen voor handmatige sloop zijn onder andere: binnensloop in krappe ruimtes waar grote machines niet passen, selectieve sloop waarbij specifieke delen behouden moeten blijven, sloop van monumentale panden waar historische elementen gespaard moeten worden, en projecten in dichtbebouwde omgevingen waar trillingen en geluidsoverlast geminimaliseerd moeten worden.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De voordelen van handmatige sloop zijn legio: maximale precisie en controle over het proces, minimale kans op beschadiging van omliggende constructies, uitstekende mogelijkheden voor materiaalscheiding en recycling, lagere geluidsproductie en trillingen, en vaak een gunstiger prijs voor kleinschalige projecten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wanneer Kiezen voor Mechanische Sloop?',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Mechanische sloop maakt gebruik van zware machines zoals sloopkranen, graafmachines met hydraulische hamers, en gespecialiseerde sloopapparatuur. Deze methode is onmisbaar voor grootschalige projecten waar snelheid en efficiëntie prioriteit hebben.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Mechanische sloop is de voorkeursmethode voor: grote industriële gebouwen en fabrieken, flatgebouwen en hoogbouw, betonnen constructies en bruggen, projecten met strakke tijdslijnen, en locaties waar ruimte geen beperking vormt.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De kracht van mechanische sloop ligt in de enorme productiviteit: een ervaren sloopkraan kan in één dag meer werk verzetten dan een team van tien handmatige slopers in een week. Daarnaast biedt mechanische sloop een hoger veiligheidsniveau bij gevaarlijke constructies waar instortingsgevaar bestaat.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Kostenvergelijking en Efficiëntie',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De kosten van sloopwerk variëren sterk afhankelijk van de gekozen methode. Handmatige sloop heeft lagere materieelkosten maar hogere arbeidskosten, terwijl mechanische sloop hogere investeringen in apparatuur vereist maar minder arbeidsuren nodig heeft.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Voor een gemiddeld woonhuis van 150m² liggen de kosten voor handmatige sloop tussen de €15.000 en €25.000, afhankelijk van de complexiteit en de hoeveelheid te recyclen materialen. Mechanische sloop van hetzelfde huis kost doorgaans €12.000 tot €20.000, maar met minder mogelijkheden voor selectieve demontage en materiaalhergebruik.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Bij grote projecten verschuift de kostenbalans snel naar mechanische sloop. Een flatgebouw van tien verdiepingen kan met mechanische apparatuur in enkele weken worden gesloopt, terwijl handmatige sloop maanden zou duren met exponentieel hogere arbeidskosten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Veiligheidsaspecten en Milieu-overwegingen',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Veiligheid staat altijd voorop bij sloopwerkzaamheden. Handmatige sloop brengt specifieke risicos met zich mee zoals vallende objecten, instortingsgevaar en blootstelling aan gevaarlijke stoffen. Onze vakmensen zijn volledig gecertificeerd en werken met persoonlijke beschermingsmiddelen en veiligheidssystemen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Mechanische sloop vereist een andere veiligheidsaanpak met afzettingen, valbeveiliging en strikte protocols voor machinisten. De afstand tussen bedienaar en slooplocatie biedt inherent meer veiligheid bij instabiele constructies.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Vanuit milieu-oogpunt scoort handmatige sloop vaak beter door de mogelijkheid tot zorgvuldige scheiding van materialen. Dit verhoogt het recyclingspercentage aanzienlijk. Mechanische sloop genereert meer gemengd puin, hoewel moderne sorteerinstallaties dit deels kunnen compenseren.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Hybride Sloop: De Beste van Beide Werelden',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In de praktijk kiezen wij vaak voor een hybride aanpak die de voordelen van beide methoden combineert. Dit betekent dat gevoelige delen handmatig worden gedemonteerd, terwijl de hoofdstructuur mechanisch wordt gesloopt. Deze strategie optimaliseert zowel de veiligheid, de kosten als het milieu-resultaat.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Een typisch voorbeeld is de renovatie van een kantoorpand waarbij de gevel en interne scheidingswanden handmatig worden verwijderd om glas en metaal zuiver te recycleren, gevolgd door mechanische sloop van de dragende betonconstructie. Deze aanpak realiseert tot 95% recycling en minimaliseert de overlast voor de omgeving.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Conclusie: Maak de Juiste Keuze voor Uw Project',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De keuze tussen handmatige en mechanische sloop hangt af van meerdere factoren: de schaal en complexiteit van het project, de beschikbare tijd en het budget, de omgeving en mogelijke overlast, duurzaamheidsdoelstellingen, en specifieke veiligheidsrisicos.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Als gespecialiseerd sloopbedrijf adviseren wij u graag over de optimale aanpak voor uw specifieke situatie. Onze experts maken een gedetailleerde risicoanalyse en kostenberekening zodat u een weloverwogen beslissing kunt nemen. Neem vandaag nog contact met ons op voor een vrijblijvende offerte en professioneel advies op maat.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Ontdek de verschillen tussen handmatige en mechanische sloop. Lees welke methode het beste bij uw project past en maak een weloverwogen keuze.',
      image: heroImage.id,
      title: 'Handmatige vs Mechanische Sloop: De Juiste Methode Kiezen',
    },
    relatedPosts: [],
    title: 'Handmatige vs Mechanische Sloop: De Juiste Methode Kiezen',
  }
}
