import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  heroImage: Media
  blockImage: Media
  author: User
}

export const post5: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'asbest-verwijdering-veiligheid',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Asbest is een van de gevaarlijkste materialen die we tegenkomen bij sloopwerkzaamheden. De fijne vezels kunnen ernstige longziekten veroorzaken, waaronder longkanker en asbestose. Professionele asbestsanering vereist daarom specialistische kennis, gecertificeerde werkwijzen en strikte veiligheidsmaatregelen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Als gecertificeerd asbestsaneeringsbedrijf met alle benodigde BRL SVS-001 certificeringen hebben wij duizenden asbestverwijderingsprojecten succesvol afgerond. In dit artikel delen wij onze expertise over veilige asbestverwijdering.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Gezondheidsrisicos van Asbestblootstelling',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Asbestvezels zijn microscopisch klein en kunnen diep in de longen doordringen wanneer ze worden ingeademd. Eenmaal in het lichaam veroorzaken ze ontstekingen en littekenvorming die kunnen leiden tot levensbedreigende ziekten. De symptomen treden vaak pas decennia na blootstelling op.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De belangrijkste asbestgerelateerde ziekten zijn: asbestose (verlittekening van het longweefsel), longkanker (bij rokers is het risico nog hoger), en mesothelioom (een zeldzame en agressieve kanker van het buikvlies of longvlies). Er is geen veilige grenswaarde voor asbestblootstelling - elke blootstelling vormt een risico.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Dit is waarom asbestverwijdering alleen door gecertificeerde professionals mag worden uitgevoerd. Zelf kleine klusjes met asbesthoudende materialen kunnen gevaarlijk zijn en zijn in Nederland wettelijk verboden zonder juiste certificering.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wettelijke Eisen en Certificeringen',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In Nederland gelden strikte regels voor asbestverwijdering. Het Besluit Asbesthoudende Materialen en de BRL SVS-001 norm beschrijven alle vereisten voor veilige asbestsanering. Alleen bedrijven met de juiste certificering mogen asbest verwijderen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Onze certificeringen omvatten: BRL SVS-001 certificering voor asbestsanering, VCA** veiligheidscertificaat, ISO 14001 milieumanagement, en erkenning door de SIKB (Stichting Infrastructuur Kwaliteitsborging Bodembeheer). Al onze asbestsaneerders zijn individueel gecertificeerd en volgen jaarlijkse hercertificering.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Voor elke asbestverwijdering moet een melding worden gedaan bij de gemeente en de Arbeidsinspectie. Wij regelen alle benodigde papierwerk en vergunningen voor onze klanten, zodat zij zich geen zorgen hoeven te maken over de bureaucratie.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Veiligheidsprocedures en Persoonlijke Bescherming',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Asbestsanering vereist strikte veiligheidsprotocollen en gespecialiseerde persoonlijke beschermingsmiddelen (PBM). Onze werkwijze garandeert maximale veiligheid voor onze medewerkers, omwonenden en het milieu.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Onze asbestsaneerders gebruiken: volledige asbestpakken met adembescherming (P3-filters), handschoenen en over-schoenen, speciale stofbrillen en gezichtsschermen, en persoonlijke luchtsmelders om de asbestconcentratie te monitoren. Na elke shift worden de pakken zorgvuldig gereinigd en gecontroleerd.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Het werkgebied wordt volledig afgesloten met plastic afdekfolie en onderdruk gehouden met speciale afzuiginstallaties. Dit voorkomt dat asbestdeeltjes het werkgebied verlaten. Alle lucht die wordt afgezogen wordt gefilterd door HEPA-filters.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Het Asbestverwijderingsproces Stap voor Stap',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Elk asbestverwijderingsproject volgt een strikt protocol dat is vastgelegd in de BRL SVS-001. Dit proces waarborgt maximale veiligheid en naleving van alle wettelijke eisen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 1: Inventarisatie en risicoanalyse. Voordat we beginnen voeren we een grondige asbestinventarisatie uit. We identificeren alle asbesthoudende materialen, bepalen de mate van beschadiging, en stellen een risicoanalyse op. Dit vormt de basis voor het saneringsplan.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 2: Voorbereiding en afzetting. Het werkgebied wordt hermetisch afgesloten met dubbele lagen plastic folie. We creëren een sluis met een driekamer systeem voor in- en uitgang. Een onderdruksysteem met HEPA-filtratie voorkomt dat asbestdeeltjes naar buiten lekken.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 3: Natte verwijdering en inpakken. Asbest wordt nooit droog verwijderd. We gebruiken water met wasmiddel om de vezels te binden en te voorkomen dat ze opwaaien. Verwijderd asbest wordt direct in gekeurde zakken of containers gesealed en gelabeld.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Stap 4: Reiniging en luchtmetingen. Na verwijdering wordt het werkgebied grondig gereinigd met speciale stofzuigers met HEPA-filters. Vervolgens voeren we luchtmetingen uit met fase-contrast-microscopie om te verifiëren dat er geen asbestvezels achterblijven.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "Stap 5: Oplevering en documentatie. Bij succesvolle metingen wordt het gebied vrijgegeven. Wij leveren een compleet pakket documentatie inclusief saneringsplan, foto's, luchtmetingsrapporten en verwerkingsbewijzen van het asbestafval.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Afvoer en Verwerkingsregels',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Asbestafval is gevaarlijk afval en moet volgens strenge regels worden verwerkt. Het mag nooit bij het huishoudelijk afval of in de container voor bouwafval. Alleen erkende asbestverwerkingsbedrijven mogen asbest in ontvangst nemen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wij werken samen met gecertificeerde verwerkers die asbest veilig storten op speciale stortplaatsen of verwerken tot onschadelijk granulaat. Voor elke lading ontvangen wij een verwerkingsbewijs dat wij aan onze klanten verstrekken. Dit is wettelijk verplicht en bewijst dat het asbest correct is verwerkt.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Waar Kan Asbest Voorkomen?',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Asbest is veel toegepast in gebouwen gebouwd tussen 1940 en 1993. Voor 1994 mag asbest nog zijn verwerkt in producten die al op de markt waren. Daarom blijft asbest een risico in oudere panden.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Veelvoorkomende toepassingen zijn: golfplaten op daken en schuren, asbestcement buizen en leidingen, vloertegels en tegellijm, kitvoegen en voegspecie, isolatiemateriaal om leidingen en ketels, en brandwerende coatings en platen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Verdachte materialen mogen nooit zelf worden gebroken of bewerkt. Laat altijd een asbestinventarisatie uitvoeren door een gecertificeerd bedrijf voordat u begint met sloop- of renovatiewerkzaamheden.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Conclusie: Veiligheid Staat Voorop',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Asbestverwijdering is specialistisch werk dat alleen door gecertificeerde professionals mag worden uitgevoerd. De gezondheidsrisicos zijn te groot om hier zelf mee aan de slag te gaan. Door te kiezen voor TitanBreakers kiest u voor veiligheid, kwaliteit en gemoedsrust.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Heeft u asbest vermoed in uw pand of heeft u asbestsanering nodig? Neem contact met ons op voor een vrijblijvende inventarisatie en offerte. Onze experts staan klaar om u te adviseren en te helpen met veilige, professionele asbestverwijdering.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Professionele gids voor veilige asbestverwijdering. Lees over gezondheidsrisicos, wettelijke eisen, veiligheidsprocedures en certificeringen.',
      image: heroImage.id,
      title: 'Veilige Asbestverwijdering: Professionele Gids',
    },
    relatedPosts: [],
    title: 'Veilige Asbestverwijdering: Professionele Gids',
  }
}
