import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  heroImage: Media
  blockImage: Media
  author: User
}

export const post6: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'duurzaam-sloopwerk',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Duurzaamheid is geen trend meer, maar een noodzaak. Ook in de sloopsector spelen milieu-overwegingen een steeds grotere rol. Bij TitanBreakers streven wij al jaren naar maximale recycling en minimale milieu-impact. Met trots kunnen wij zeggen dat wij vandaag 98% van alle sloopmaterialen recyclen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In dit artikel delen wij onze visie op duurzaam sloopwerk en hoe wij bijdragen aan een circulaire economie. Ontdek hoe bouwafval wordt omgetoverd tot waardevolle grondstoffen en hoe u bijdraagt aan een groenere toekomst door te kiezen voor duurzame sloop.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Waarom Duurzaam Sloopwerk Belangrijk Is',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De bouwsector is verantwoordelijk voor een aanzienlijk deel van het nationale afval. Traditioneel belandde het grootste deel van dit afval op stortplaatsen, met grote milieu-impact tot gevolg. Gelukkig is daar de laatste jaren veel verandering in gekomen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Door materialen te recycleren en te hergebruiken reduceren we de vraag naar nieuwe grondstoffen. Dit bespaart energie, reduceert CO2-uitstoot en beschermt natuurlijke hulpbronnen. Bovendien creëert het economische waarde en banen in de recyclingsector.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De Nederlandse overheid stimuleert duurzaam sloopwerk met steeds strengere regelgeving. De doelstelling is om in 2030 100% van het bouwafval te recyclen. Wij lopen hierop vooruit en hebben die ambitie al bijna bereikt.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Hoe Wij 98% Recycling Realiseren',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Het behalen van een 98% recyclingpercentage vereist een geïntegreerde aanpak vanaf het eerste moment van het sloopproject. Wij beginnen al bij de ontwerpfase met het bepalen van de meest duurzame sloopmethode.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Onze aanpak bestaat uit drie pijlers: selectieve sloop, zorgvuldige materiaalscheiding op de bouwplaats, en samenwerking met gespecialiseerde verwerkers. Door handmatig te demonteren waar mogelijk, houden we materialen zuiver en bruikbaar.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Op de bouwplaats hebben we verschillende containerstromen voor elk materiaaltype: hout, metaal, beton, kunststof, glas en gips. Dit voorkomt vermenging en verontreiniging, waardoor het hergebruikpercentage optimaal blijft.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Materiaalstromen en Verwerking',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Elk materiaal dat wij slopen volgt een eigen route naar hergebruik. Door samen te werken met hoogwaardige verwerkers weten wij zeker dat materialen optimaal worden benut.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Hout wordt gesorteerd op kwaliteit en bestemming. Schoon hout wordt verwerkt tot nieuwe plaatmaterialen of biomassa voor energie-opwekking. Beton en puin worden gebroken en gebruikt als granulaat voor wegenbouw en funderingen. Metalen worden gesmolten en vormen de grondstof voor nieuwe staal- en aluminiumproducten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Kunststoffen worden per type gescheiden en gerecycled tot nieuwe producten zoals parket, kabelgoten of verpakkingsmaterialen. Glas wordt gerecycled tot nieuw glas of glaswol-isolatie. Zelfs gips kan worden gerecycled tot nieuwe gipsplaten of grondstabilisator.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Milieuwinst en CO2-Reductie',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Het milieu profiteert enorm van duurzaam sloopwerk. Door recycling besparen we jaarlijks duizenden tonnen CO2. Voor elke ton gerecycled beton besparen we circa 50 kg CO2. Metaalrecycling bespaart nog meer: tot 95% van de energie die nodig is voor nieuwe productie.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Daarnaast reduceren wij onze eigen ecologische voetafdruk. Ons wagenpark bestaat voor 60% uit elektrische en hybride machines. We optimaliseren transportroutes en plannen efficiënt om vrachtbewegingen te minimaliseren. Onze kantoren en bedrijfspanden draaien op groene stroom.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'In 2025 streven wij naar volledig CO2-neutrale operaties. Dit doen we door verdere elektrificatie, investering in zonne-energie, en CO2-compensatie van resterende uitstoot door bosbehoudprojecten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Circulaire Economie in de Sloopsector',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De circulaire economie draait om het sluiten van kringlopen: afval wordt grondstof voor nieuwe producten. In de sloopsector betekent dit dat we niet alleen recycleren, maar ook streven naar hergebruik van complete bouwelementen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wij werken samen met marktplaatsen voor gebruikte bouwmaterialen. Goed onderhouden deuren, kozijnen, sanitair en keukens krijgen een tweede leven in andere projecten. Dit is het meest duurzame gebruik van materialen: direct hergebruik zonder energie-intensieve recycling.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Door onze 3D-scanning technologie kunnen we materialen al voor de sloop inventariseren en matchen met vraag uit andere projecten. Dit is next-level circulair bouwen: precies weten welke materialen beschikbaar komen en deze tijdig vermarkten.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Certificeringen en Kwaliteitsgarantie',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ons duurzaamheidsbeleid is onafhankelijk gecertificeerd. Wij beschikken over: ISO 14001 certificering voor milieumanagement, CO2-Prestatieladder niveau 3, BREEAM-assessor certificering voor duurzaam bouwen, en erkenning als circulair sloopbedrijf door het ministerie van IenW.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Voor elk project leveren wij een milieu-impactrapport met statistieken over recyclingpercentages, CO2-besparingen en verwerkingsroutes. Zo kunt u aantonen dat uw project bijdraagt aan duurzaamheidsdoelstellingen.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Conclusie: Bouw Mee aan een Groene Toekomst',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Duurzaam sloopwerk is de toekomst. Door te kiezen voor TitanBreakers kiest u niet alleen voor professionele sloop, maar ook voor een groenere planeet. Met onze 98% recycling en ambitieuze CO2-doelstellingen zijn wij koploper in duurzame demontage.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Wilt u meer weten over onze duurzame werkwijze of een offerte aanvragen voor circulaire sloop? Neem contact met ons op. Samen zorgen we ervoor dat uw sloopproject een positieve bijdrage levert aan het milieu. Kies voor duurzaam, kies voor TitanBreakers.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Ontdek alles over duurzaam sloopwerk. Lees hoe wij 98% van onze materialen recycleren en bijdragen aan een circulaire economie.',
      image: heroImage.id,
      title: 'Duurzaam Sloopwerk: Bouw Mee aan een Groenere Toekomst',
    },
    relatedPosts: [],
    title: 'Duurzaam Sloopwerk: Bouw Mee aan een Groenere Toekomst',
  }
}
