import { RequiredDataFromCollectionSlug } from 'payload'
import type { PostArgs } from './post-1'

export const post2: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'keuken-sloop-gids',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Een keukenrenovatie begint met professionele sloop. Deze gids legt alles uit over het slopen van keukens: van voorbereiding tot oplevering.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Voordelen van Professionele Keuken Sloop',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '✓ Veilig omgaan met gas-, water- en elektraleidingen\n✓ Bescherming van dragende wanden en constructies\n✓ Juiste asbestinventarisatie en verwijdering\n✓ Zorgvuldige materiaalscheiding voor recycling\n✓ Garantie op vakmanschap en veiligheid\n✓ Snelle en efficiënte uitvoering',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Risicos van Zelf Slopen',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '✗ Gevaar van gaslekken en explosierisico\n✗ Risico op waterschade door lekkende leidingen\n✗ Kortsluiting en brandgevaar bij elektrawerk\n✗ Blootstelling aan asbest zonder bescherming\n✗ Beschadiging van vloeren en omliggende ruimtes\n✗ Geen verzekeringsdekking bij ongelukken',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Ons Sloopproces',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Fase 1: Inventarisatie en afsluiten nutsvoorzieningen\nFase 2: Verwijderen van apparaten en kasten\nFase 3: Slopen van tegelwanden en werkbladen\nFase 4: Veilig afkappen van leidingen\nFase 5: Schoonmaak en afvalscheiding',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Kosten en Tijdsplanning',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'De kosten voor professionele keukensloop liggen tussen €800 en €2.500, afhankelijk van de grootte en complexiteit. Een standaard keuken wordt doorgaans binnen 1-2 dagen volledig gesloopt en opgeleverd.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Ontdek alles over professionele keukensloop. Van voorbereiding tot duurzame afvalverwerking - wij regelen het complete sloopproces voor uw keukenrenovatie.',
      image: heroImage.id,
      title: 'Complete Gids voor Professionele Keuken Sloop',
    },
    relatedPosts: [],
    title: 'Complete Gids voor Professionele Keuken Sloop',
  }
}
